platform :ios, '8.0'
target ‘swiftNetTry’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SVProgressHUD', '~> 2.2.1'
end
